# Site settings
title:            bigwhiteshark's Personal Blog
name:             bigwhiteshark
email:            bigwhiteshark@163.com
description:      bigwhiteshark's Personal Blog
baseurl:          ""
url:              http://bigwhiteshark.github.com
twitter_username: bigwhiteshark
github_username:  bigwhiteshark
github_url:       https://github.com/bigwhiteshark/bigwhiteshark.github.io
lang:             zh
timezone:         Asia/Beijing
google_verify:    RT539FF0rbiuLpZhJ03luXudbWRnqQT3B-NFKaqY6TA
google_plus:      117687312367284657910

# Handling Reading
safe:         false
encoding:     "utf-8"
permalink:    pretty

sass:
    style: :compressed

gems:
    - jekyll-sitemap
    - jekyll-feed

exclude: ["README.md"]

# Default layout
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Conversion
highlighter: rouge
#highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - lax_spacing
    #- no_fenced_code_blocks
    - syntax_highlighter_opts
    - tables

# markdown: kramdown
# kramdown:
#   input:         GFM
#   auto_ids:      true
#   auto_id_prefix: 'id-'

excerpt_separator: "<!--more-->"




